### ISSUE TITLE
Listado del app.out

### ISSUE THREAD

**Issue by IvanSzkrabko** [cese-ids/cese-ids-12Co-tp1a#1]
Buenas,
Antes de pushear mis cambios al repo compile el proyecto como venia y note que algunas serializaciones se repiten (ver imagen adunta), revise el codigo rapidamente pero no encontre el problema :/ ... no se en que comit empezo a pasar

![Weird](https://user-images.githubusercontent.com/8770705/86516288-a9b3ee00-bdf5-11ea-8c56-6a02b7948486.png)

**Comment by ronalcelaya** [comment]
Hola!

Recién hice pull y no tengo esos problemas

![image](https://user-images.githubusercontent.com/5035608/86517264-f3083b80-bdfd-11ea-85cf-0e42dbc22180.png)

**Comment by IvanSzkrabko** [comment]
Que raro che, no entiendo que puede ser ... guarde el zip que me habia descargado por si alguno mas lo quiere correr y ver si le pasa lo mismo

[cese-ids-12Co-tp1a-master.zip](https://github.com/cese-ids/cese-ids-12Co-tp1a/files/4873719/cese-ids-12Co-tp1a-master.zip)

**Comment by facalcavec** [comment]
Hola, a mi me paso lo mismo y me parece que es, que cuando vos haces el merge, un montón de llaves y lineas de programa desaparecen (no las tuyas, sino anteriores) y que si no las corregis te aparece eso, hasta que otro pushee el codigo corregido, se arrastran esos errores en el master.
